In [33]:
weights = torch.Tensor([1, 2, 3, 4, 99, 99999, -2])   # 采样权重
torch.multinomial(weights, 10, replacement=True)

RuntimeError: invalid multinomial distribution (encountering probability entry < 0)

In [25]:
import torch

z = torch.tensor([[[[1.,2.,3.],[4.,4.,5.]],[[6.,8.,8.],[9.,5.,7.]]]])
z.contiguous().view(-1)
z

tensor([[[[1., 2., 3.],
          [4., 4., 5.]],

         [[6., 8., 8.],
          [9., 5., 7.]]]])

In [18]:
import torch
from torch import Tensor
from torch.nn import Module

from torch import _VF


# X = torch.tensor([[1.,2.,3.],[4.,4.,5.],[6.,8.,8.],[9.,5.,7.]])
# p0 = 0.4
# p1 = 0.6
# p05 = 1- p0 - p1
# training = True

def dropout(X, p0, p1, training, inplace=False):
    p05 = 1 - p0 - p1
    # print(X.sum())
    weights = torch.Tensor([p0, p05, p1])   # 采样权重
    mask = torch.multinomial(weights, len(X.view(-1)), replacement=True)
    mask = mask.view(X.shape)/2
    # print((mask * X / (0*p0 + 0.5*p05 + 1*p1)).sum())
    return mask * X / (0*p0 + 0.5*p05 + 1*p1)

# dropout(X, p0, p1, training)


class _DropoutNd(Module):
    __constants__ = ['p', 'inplace']
    p: float
    inplace: bool

    def __init__(self, p1: float = 0.2, p2: float = 0.2, inplace: bool = False) -> None:
        super(_DropoutNd, self).__init__()
        # if p < 0 or p > 1:
        #     raise ValueError("dropout probability has to be between 0 and 1, "
        #                      "but got {}".format(p))
        self.p1 = p1
        self.p2 = p2
        self.inplace = inplace

    # def extra_repr(self) -> str:
    #     return 'p={}, inplace={}'.format(self.p, self.inplace)


class Dropout(_DropoutNd):
    def forward(self, input: Tensor) -> Tensor:
        return dropout(input, self.p1, self.p2, self.training, self.inplace)

import torch
do = Dropout(0.2, 0.4)
input_ = torch.tensor([[1.,2.,3.],[4.,4.,5.],[6.,8.,8.],[9.,5.,7.]])
do(input_)

tensor([[ 1.6667,  1.6667,  2.5000],
        [ 3.3333,  3.3333,  8.3333],
        [ 5.0000,  0.0000, 13.3333],
        [ 7.5000,  8.3333, 11.6667]])

In [ ]:
def dropout(X, p0, p1, training):

    a = dropout_rate
    b = 1 - dropout_rate
    
    mask = torch.tensor(beta.rvs(a, b, size=tuple(X.shape)).astype(np.float32))
    mask = mask.to(torch.device("cuda"))  # .float()
    
    return mask * X * (X.sum() / (mask * X).sum())

In [ ]:
from scipy.stats import multinomial

In [6]:
y = torch.tensor([[1.,2.,3.,4.],[4.,5.,6.,8.]])


In [12]:
len(y.view(-1))

8

In [11]:
y

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 8.]])

In [ ]:
tuple(X.shape)

In [ ]:
multinomial.rvs(n=9,p=(0.3, 0.4, 0.1, 0.1),size=1, replacement=True)

In [ ]:
import inspect

inspect.getfullargspec(multinomial.rvs)

In [ ]:
import torch

def dropout(X, p0, p1, training):

    a = dropout_rate
    b = 1 - dropout_rate
    
    mask = torch.tensor(beta.rvs(a, b, size=tuple(X.shape)).astype(np.float32))
    mask = mask.to(torch.device("cuda"))  # .float()
    
    return mask * X * (X.sum() / (mask * X).sum())

In [ ]:
from torch import Tensor
from torch.nn import Module

from torch import _VF

def dropout(input: Tensor, p: float = 0.5, training: bool = True, inplace: bool = False) -> Tensor:
    # if has_torch_function_unary(input):
    #     return handle_torch_function(dropout, (input,), input, p=p, training=training, inplace=inplace)
    if p < 0.0 or p > 1.0:
        raise ValueError("dropout probability has to be between 0 and 1, " "but got {}".format(p))
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)

class _DropoutNd(Module):
    __constants__ = ['p', 'inplace']
    p: float
    inplace: bool

    def __init__(self, p: float = 0.5, inplace: bool = False) -> None:
        super(_DropoutNd, self).__init__()
        if p < 0 or p > 1:
            raise ValueError("dropout probability has to be between 0 and 1, "
                             "but got {}".format(p))
        self.p = p
        self.inplace = inplace

    def extra_repr(self) -> str:
        return 'p={}, inplace={}'.format(self.p, self.inplace)


class Dropout(_DropoutNd):
    def forward(self, input: Tensor) -> Tensor:
        return dropout(input, self.p, self.training, self.inplace)

import torch
do = Dropout(0.5)
input_ = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
do(input_)