In [8]:
import torch
torch.load('./checkpoint_epoch_80_multinomial.pth')['model_state']
# 'model_state'

OrderedDict([('global_step', tensor([117392], device='cuda:1')),
             ('vfe.pfn_layers.0.linear.weight',
              tensor([[-7.7977e-03,  7.7356e-04, -7.1602e-01, -3.6067e+00,  8.6995e-02,
                       -1.0852e-01, -2.4284e-01, -2.7035e-01,  3.1120e-01,  6.2121e-01],
                      [-8.0679e-02, -2.4397e-02,  2.5871e-01, -1.1243e-02,  8.2153e-02,
                        1.4491e-01,  3.6067e-01,  5.6139e-03, -1.1637e-01, -6.4958e-01],
                      [-9.1476e-03, -1.4062e-02,  4.2316e-01, -4.0525e-01,  3.8666e-01,
                        2.3786e-01,  5.8192e-01,  4.1385e-01,  9.4790e-02, -1.0105e+00],
                      [-2.7122e-02,  1.5328e-01, -2.8148e-01, -1.4102e-01,  4.0307e+00,
                       -2.4806e+00, -2.2582e-02,  2.6920e+00, -2.2134e+00, -1.5535e+00],
                      [-9.5503e-03, -1.9062e-03,  4.3710e-01, -4.8426e-01,  1.9428e-01,
                        1.5379e-01,  4.7047e-01,  3.7030e-01, -9.6222e-02, -9.4285e-01],
  

In [9]:
torch.load('./checkpoint_epoch_80_multinomial.pth')['model_state']

AttributeError: 'collections.OrderedDict' object has no attribute 'cuda'

In [35]:
a=torch.load('./save_path/0722/ckpt_epoch1.pth')
b=torch.load('./checkpoint_epoch_80_multinomial.pth', map_location=torch.device('cuda:0'))['model_state']

In [25]:
# a.equal(b)          
a.keys() == b.keys()

True

In [36]:
for i in a.keys():
    if not a[i].equal(b[i]):
        print('!!!'+i)
    else:
        print(i)

global_step
!!!vfe.pfn_layers.0.linear.weight
!!!vfe.pfn_layers.0.norm.weight
!!!vfe.pfn_layers.0.norm.bias
!!!vfe.pfn_layers.0.norm.running_mean
!!!vfe.pfn_layers.0.norm.running_var
!!!vfe.pfn_layers.0.norm.num_batches_tracked
!!!backbone_2d.blocks.0.1.weight
!!!backbone_2d.blocks.0.2.weight
!!!backbone_2d.blocks.0.2.bias
!!!backbone_2d.blocks.0.2.running_mean
!!!backbone_2d.blocks.0.2.running_var
!!!backbone_2d.blocks.0.2.num_batches_tracked
!!!backbone_2d.blocks.0.5.weight
!!!backbone_2d.blocks.0.6.weight
!!!backbone_2d.blocks.0.6.bias
!!!backbone_2d.blocks.0.6.running_mean
!!!backbone_2d.blocks.0.6.running_var
!!!backbone_2d.blocks.0.6.num_batches_tracked
!!!backbone_2d.blocks.0.9.weight
!!!backbone_2d.blocks.0.10.weight
!!!backbone_2d.blocks.0.10.bias
!!!backbone_2d.blocks.0.10.running_mean
!!!backbone_2d.blocks.0.10.running_var
!!!backbone_2d.blocks.0.10.num_batches_tracked
!!!backbone_2d.blocks.0.13.weight
!!!backbone_2d.blocks.0.14.weight
!!!backbone_2d.blocks.0.14.bias
!!!back

NameError: name 'model' is not defined

In [30]:
a['vfe.pfn_layers.0.norm.running_mean']

tensor([-2.9298e-02, -1.4331e-01, -6.3301e-02,  3.6923e-04, -6.8433e-02,
        -2.7066e-01, -1.0506e-01, -3.3586e-01,  2.2767e-02, -3.8293e-01,
        -6.0793e-03, -5.8465e-02, -4.3671e-01, -2.3949e-01,  3.9981e-03,
        -2.4494e-01, -1.5297e-01,  1.8088e-01, -2.3583e-01, -3.3207e-02,
        -1.6827e-01, -2.5069e-02, -1.8686e-01,  2.2241e+00, -7.8211e-01,
        -1.6131e-02, -6.2778e-03, -2.7407e-01, -4.6310e-01, -2.1492e-03,
        -1.6258e-01, -5.5519e-01,  1.4755e-01, -5.5428e-02,  3.9439e-02,
        -6.0756e-02, -5.2769e-01, -2.3450e-01, -2.0216e-01, -1.0603e-01,
        -4.2330e-01,  1.1397e-02, -3.6214e-03,  1.1810e-02,  3.0258e-02,
         1.9056e-02, -9.9186e-02, -1.9987e-01, -1.2649e-01, -6.5135e-02,
        -1.4424e-01, -2.1227e-01, -6.2412e-02, -8.9517e-04, -3.6309e-01,
        -2.7351e-01,  2.5848e-02, -5.2222e-02, -1.0182e-01,  3.7101e-03,
        -5.0956e-01,  1.6641e-01, -6.8377e-02, -2.0136e-01], device='cuda:0')

In [31]:
b['vfe.pfn_layers.0.norm.running_mean']

tensor([-2.8585e-02, -1.4505e-01, -6.4647e-02,  2.1612e-03, -7.0273e-02,
        -2.6801e-01, -1.0428e-01, -3.4920e-01,  2.5184e-02, -3.8563e-01,
        -1.0347e-02, -5.9224e-02, -4.3949e-01, -2.3996e-01,  4.7094e-03,
        -2.4644e-01, -1.5353e-01,  1.8159e-01, -2.2789e-01, -3.6829e-02,
        -1.6905e-01, -1.6111e-02, -1.8765e-01,  2.2387e+00, -7.8655e-01,
        -8.2320e-03, -5.9897e-03, -2.7574e-01, -4.6753e-01, -3.9739e-03,
        -1.6351e-01, -5.5405e-01,  1.4731e-01, -5.7715e-02,  3.7653e-02,
        -6.0694e-02, -5.3037e-01, -2.3449e-01, -2.0292e-01, -1.0258e-01,
        -4.2049e-01,  1.2666e-02, -3.0856e-03,  8.8610e-03,  2.5953e-02,
         1.5521e-02, -1.0010e-01, -2.0095e-01, -1.2709e-01, -6.4487e-02,
        -1.3573e-01, -2.0680e-01, -6.0088e-02, -4.0408e-03, -3.6512e-01,
        -2.7427e-01,  2.6388e-02, -5.2993e-02, -9.7009e-02,  1.8403e-03,
        -5.1206e-01,  1.6840e-01, -6.8746e-02, -2.1132e-01], device='cuda:0')

In [19]:
loaded#['global_step']

OrderedDict([('global_step', tensor([112752], device='cuda:1')),
             ('vfe.pfn_layers.0.linear.weight',
              tensor([[-7.7232e-03, -3.3648e-04, -7.2581e-01, -3.6653e+00,  4.5908e-02,
                       -1.4569e-01, -2.5837e-01, -3.0689e-01,  3.2346e-01,  6.1266e-01],
                      [-8.2013e-02, -2.4800e-02,  2.6299e-01, -1.1429e-02,  8.3512e-02,
                        1.4731e-01,  3.6663e-01,  5.7068e-03, -1.1829e-01, -6.6032e-01],
                      [-1.2959e-02, -6.3140e-04,  4.7489e-01, -4.5970e-01,  4.1164e-01,
                        2.0495e-01,  5.8051e-01,  4.3293e-01,  4.7608e-02, -9.8186e-01],
                      [-2.5788e-02,  1.5084e-01, -2.9588e-01, -1.3917e-01,  4.0326e+00,
                       -2.5082e+00, -2.7951e-02,  2.7280e+00, -2.2529e+00, -1.5896e+00],
                      [-9.4229e-03, -7.1227e-05,  4.8303e-01, -5.3987e-01,  1.7215e-01,
                        1.8806e-01,  4.5461e-01,  3.5728e-01, -6.3457e-02, -9.2505e-01],
  